version: '3.7'
services:
  db:
    image: postgres
    container_name: postgres_${APP_NAME}
    volumes:
      - ${DB_LOCATION}:/var/lib/postgresql/data
    ports: 
      - "5432:5432"
    networks:
      mynet:
    environment: 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  web:
    build: .
    image: ${APP_NAME}
    command: bash -c "rm -f tmp/pids/server.pid && yarn install --check-files && bundle install && RAILS_ENV=${DEPLOYMENT_STAGE} rails db:migrate && RAILS_ENV=${DEPLOYMENT_STAGE} bundle exec rails s -p 3000 -b '0.0.0.0'"
    container_name: ${APP_NAME}
    volumes:
      - .:/app
      - ${DATA_LOCATION}:/app/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks: 
      mynet:

networks: 
  mynet:
    external: 
      name: ${APP_NAME}_network